services:
  - name: fastapi-app
    buildCommand: |
      pi-env\scripts\Activate.bat
      pip install -r Fastapi-deploy/requirements.txt
    startCommand: uvicorn Fastapi-deploy.main:app --host 0.0.0.0 --port $PORT
    env:
      - key: PYTHONUNBUFFERED
        value: '1'