services:
  - name: fastapi-app
    buildCommand: |
      source pi-env/proyecth/bin/activate
      pip install -r Fastapi-deploy/requirements.txt
    startCommand: uvicorn fastapi-deployment.main:app --host 0.0.0.0 --port $PORT
    env:
      - key: PYTHONUNBUFFERED
        value: '1'