services:
  - name: fastapi-app
    buildCommand: |
      source Fastapi-deploy/pi-env/Scripts/activate
      pip install -r requirements.txt
    startCommand: uvicorn Fastapi-deploy.main:app --host 0.0.0.0 --port $PORT
    env:
      - key: PYTHONUNBUFFERED
        value: '1'


